services:
  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:v3.7.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prom_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090" # 9090:9090
    networks: [monitoring]
    restart: unless-stopped

  # --- Grafana ---
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      # - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "${GRAFANA_PORT}:3000" # 3000:3000
    depends_on: [prometheus]
    networks: [monitoring]
    restart: unless-stopped

  # --- MySQL (LTS 8.4.x) ---
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306" # 3306:3306
    networks: [monitoring]
    restart: unless-stopped

  # --- MySQL Exporter ---
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: mysqld-exporter
    depends_on:
      - mysql
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${MYSQL_EXPORTER_PASSWORD}
    command:
      - '--mysqld.address=${MYSQL_HOST}:${MYSQL_PORT}' # '--mysqld.address=mysql:3306'
      - '--mysqld.username=${MYSQL_EXPORTER_USER}'
    ports:
      - "9104:9104"
    networks:
      - monitoring
    restart: unless-stopped

  # --- Node Exporter (hôte) ---
  node-exporter-host:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter-host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "${NODE_EXPORTER_HOST_PORT}:9100" # "9100:9100"
    networks: [monitoring]
    restart: unless-stopped

  # --- Node Exporter (2e "nœud") ---
  node-exporter-node2:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter-node2
    # command:
    #   - '--collector.disable-defaults=false'
    ports:
      - "${NODE_EXPORTER_NODE2_PORT}:9100" # "9101:9100"
    networks: [monitoring]
    restart: unless-stopped

  # --- Alertmanager ---
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    ports:
      - "${ALERTMANAGER_PORT}:9093" # "9093:9093"
    networks: [monitoring]
    restart: unless-stopped

  demo-app:
    image: quay.io/brancz/prometheus-example-app:v0.3.0
    container_name: demo-app
    ports:
      - "${DEMO_APP_PORT}:8080" # "8080:8080"
    networks: [monitoring]
    restart: unless-stopped

  # --- Loki ---
  loki:
    image: grafana/loki:3.5.7
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    ports:
      - "${LOKI_PORT}:3100" # "3100:3100"
    networks: [monitoring]
    restart: unless-stopped

  # --- Promtail ---
  promtail:
    image: grafana/promtail:3.5.7
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./loki/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "${PROMTAIL_PORT}:9080" # "9080:9080"
    networks: [monitoring]
    depends_on: [loki]
    restart: unless-stopped

networks:
  monitoring:

volumes:
  prom_data:
  grafana_data:
  mysql_data:
  alertmanager_data:
  loki_data:
