auth_enabled: false

server:
  http_listen_port: 3100

# Réglages communs + préfixe pour tous les chemins Loki dans le volume /loki
common:
  path_prefix: /loki
  instance_addr: 127.0.0.1
  storage:
    filesystem: {}        # OK pour 3.x
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

# Structured Metadata désactivée tant qu'on n'est pas en index tsdb
limits_config:
  allow_structured_metadata: false

# Chemins requis par boltdb-shipper (index + cache)
storage_config:
  filesystem:
    directory: /loki/chunks           # <- remplace chunks_directory/rules_directory
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093